### ISSUE TITLE
Dim Desktop issues with corners and with no bar

### ISSUE THREAD

**Issue by MrDowntempo** [noctalia-dev/noctalia-shell#150]
I like the dim desktop feature! However I noticed that it doesn't play nice if you've got show corners enabled as well. Meaning it dims the corners too even though the bar the corners are connected to don't dim. This is just a minor thing that you aren't likely to notice unless you're looking for it.

However, if you've got the bar turned off on a monitor, and dim desktop activated, it doesn't dim the area where the bar would be if it were enabled.

**Comment by Ly-sec** [comment]
This commit [7b63b69](https://github.com/noctalia-dev/noctalia-shell/commit/7b63b6900d396690a530576ca0df88538c72009c) should fix it. Since I do not have a second display though I can't really test the full screen dimming.
Please close the issue if everything works, else just let us know.

//edit I see I made a mistake, reverted it for now. Going to look at it closer

**Comment by MrDowntempo** [comment]
I assume it didn't make it to 2.3.1 'cause its still not working in 2.3.1 And monitors without the bar don't get dimmed at all any longer.

**Comment by Ly-sec** [comment]
> I assume it didn't make it to 2.3.1 'cause its still not working in 2.3.1 And monitors without the bar don't get dimmed at all any longer.

Sadly correct, it's a big mess with the dimming, perhaps we can figure something out the coming days.
I expected it to be something really simple but nope.

**Comment by ItsLemmy** [comment]
This should be ok now in 2.5.0 and upward.   There is still an edge case when the bar is semitransparent and you have corners on. The dimming darken the corner. But this cant be fixed for now.
