### ISSUE TITLE
[Bug] Icons missing, but only on some things?

### ISSUE THREAD

**Issue by jacobrreed** [noctalia-dev/noctalia-shell#437]
### Description
You can see here the task bar widget showing purple/black grid icons for firefox, when the active window shows firefox icon

### Steps to Reproduce
1.  Not sure how to reproduce this because if i kill quickshell and restart the config the icons show
2.  I have set the env variables from FAQ for gtk theme and icons

### Expected Behavior
Expect icons to always show or at least fallback to something not so ugly

### Screenshots
<img width="1751" height="41" alt="Image" src="https://github.com/user-attachments/assets/85dcf119-8e9a-4887-9925-4d641927f1b4" />

### Environment
- Distro:  Arch
- Compositor: Hyprland
- Noctalia-shell Version: (not actually using noctalia-shell, but pulled repo and running it manually (because I have some custom tweaks mostly to theme but nothing touching icons)

**Comment by Ly-sec** [comment]
Hmm I can't replicate it with Firefox. I'm using [MoreWaita](https://github.com/somepaulo/MoreWaita) as the icon theme. Can you perhaps try that and see if that solves it?

**Comment by neonvoidx** [comment]
> Hmm I can't replicate it with Firefox. I'm using [MoreWaita](https://github.com/somepaulo/MoreWaita) as the icon theme. Can you perhaps try that and see if that solves it?

<img width="3411" height="1429" alt="Image" src="https://github.com/user-attachments/assets/2728334c-b2a0-496c-8dd8-b8b866846d01" />
Nope doesnt seem to matter.
Also you can see here, I have 2 kitty terminal windows side by side, its showing icon for one but for the other its the pink and black, so it's not like its actually missing the icon, it just seems to fail to look it up properly or something

**Comment by ItsLemmy** [comment]
I believe this was fixed via discord with ```QT_QPA_PLATFORMTHEME=gtk3```

**Comment by neonvoidx** [comment]
> I believe this was fixed via discord with `QT_QPA_PLATFORMTHEME=gtk3`

ya mostly, still seeing icons missing sometimes or falling back to empty icons that arent the purple/black square, but reloaded quickshell seems to fix, idk whats going on but probably not worth investigation
